version: "3.9"
services:
  spring_boot_lab1:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=movies_db
      - DATABASE_PORT=3306
  mysql_db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=movies_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  fastapi_lab2:
    image: fastapi:latest
    ports:
      - "8000:8000"
volumes:
  db:
    driver: local